//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJooleWebsiteEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechSpecFilter
    {
        public string Property_ID { get; set; }
        public string Subcategory_ID { get; set; }
        public Nullable<int> min_value { get; set; }
        public Nullable<int> max_value { get; set; }
    
        public virtual tblProperty tblProperty { get; set; }
        public virtual tblSubcategory tblSubcategory { get; set; }
    }
}
