//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJooleWebsiteEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string User_id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Profile_IMG { get; set; }
        public string User_Email { get; set; }
        public string Field { get; set; }
    }
}
